apiVersion: v1
kind: ConfigMap
metadata:
  name: lubelogger-configmap
data:
  userConfig:
    Logging:
      LogLevel:
        # -- Specifies the default log level for all components.
        # Valid levels are `Trace`, `Debug`, `Information`,
        # `Warning`, `Error`, `Critical` and `None`. Learn more at:
        # https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/
        Default: Information
        # -- Sets the log level for Microsoft.AspNetCore-related components.
        # Valid levels are `Trace`, `Debug`, `Information`,
        # `Warning`, `Error`, `Critical` and `None`. Learn more at:
        # https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/
        Microsoft.AspNetCore: Warning
    # -- Specifies allowed hosts for the application (use "*" to allow all hosts).
    AllowedHosts: "*"
    # -- Enables or disables dark mode in the user interface.
    UseDarkMode: false
    # -- Enables the ability to import data from CSV files.
    EnableCsvImports: true
    # -- Configures whether to use miles per gallon (MPG) as the fuel economy unit.
    UseMPG: false
    # -- Determines if lists are ordered in descending order by default.
    UseDescending: true
    # -- Enables or disables authentication for the application.
    EnableAuth: false
    # -- Determines whether zero values should be hidden in the UI.
    HideZero: false
    # -- Automatically refreshes reminders without manual intervention.
    EnableAutoReminderRefresh: false
    # -- Automatically inserts odometer readings based on previous data.
    EnableAutoOdometerInsert: true
    # -- Enables tracking of shop supplies in transactions.
    EnableShopSupplies: false
    # -- Enables additional columns for extra field entries.
    EnableExtraFieldColumns: false
    # -- Uses UK miles per gallon (UK MPG) as the fuel economy unit.
    UseUKMPG: false
    # -- Enables displaying gas costs with three decimal places for accuracy.
    UseThreeDecimalGasCost: true
    # -- Allows saved notes to support markdown formatting.
    UseMarkDownOnSavedNotes: false
    # -- Hides vehicles marked as sold from the display.
    HideSoldVehicles: false
    # -- Specifies the preferred unit for gas mileage.
    PreferredGasMileageUnit: "km/l"
    # -- Stores user preferences for column visibility.
    UserColumnPreferences: []
    # -- Specifies the preferred unit for gas volume.
    PreferredGasUnit: "l"
    # -- Defines the user's language preference (e.g., "en_US").
    UserLanguage: en_US
    # -- Specifies which tabs are visible in the user interface.
    VisibleTabs: [0, 1, 4, 2, 3, 6, 5, 8]
    # -- Sets the default tab to be shown when the application starts.
    DefaultTab: 8
