apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-iii
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefly-iii
  template:
    metadata:
      labels:
        app: firefly-iii
    spec:
      containers:
        - name: firefly-iii
          image: fireflyiii/core:version-6.4.9
          env:
            APP_ENV: production
            APP_DEBUG: false
          envFrom:
            - secretRef:
                name: firefly-iii-container-env
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/var/www/html/storage/upload"
              name: firefly-iii-upload
      volumes:
        - name: firefly-iii-upload
          persistentVolumeClaim:
            claimName: firefly-iii-storage
